### PR TITLE
Added mvn 3.3.3 to ITs

### PR DESCRIPTION
**Pull request by cstamas**
Introduced Maven 3.3.3 to ITs to exercise the plugin.

CI
http://bamboo.s/browse/NX-MVNF12

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by cstamas** [comment]
Staging ITs are way too long running, but for the simple reason: they _multiply_ tests based on this:

MavenVersions _x_ MavenProjectSetupMode 

MavenProjectSetupMode are:
- POM set up in ["maven2 compatible" way](https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin#maven-2--3-living-together)
- POM set up in ["maven2 only" way](https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin#maven3-only)

MavenVersions currently are:
- 2.2.1
- 3.0.5
- 3.1.1
- 3.2.3
- 3.3.3

This is basically 2 x 5 = 10 repeats for every "scenario" we have in there.

I would rather keep the three "base" maven versions: 2.2.1 (the "old one"), 3.0.5 (the "sonatype" Aether one), and 3.3.3 (latest stable).

**Comment by cstamas** [comment]
http://bamboo.s/browse/NX-MVNF12-1 :+1:

**Pull request closed without merging**
